import {Component, Inject, OnInit} from '@angular/core';
import {MatDialog, MatDialogRef, MAT_DIALOG_DATA} from '@angular/material/dialog';
import {countSectionFromBackendLevel} from '@app/editor/utils/articleBasicStructure';

@Component({
  selector: 'app-choose-section',
  templateUrl: './choose-section.component.html',
  styleUrls: ['./choose-section.component.scss']
})
export class ChooseSectionComponent implements OnInit {

  showError = false;
  sectionTemplates: any[] = [];
  value = undefined

  constructor(
    public dialog: MatDialog,
    private dialogRef: MatDialogRef<ChooseSectionComponent>,
    @Inject(MAT_DIALOG_DATA) public data: { templates: any[], sectionlevel: number },
  ) {

  }

  ngOnInit(): void {

  }

  ngAfterViewInit(): void {
    this.data.templates.push({
      "id": 9999,
      "name": "[MM] Taxon",
      "label": "Taxon",
      "schema": {
        "components": [{
          "label": "Columns",
          "columns": [{
            "components": [{
              "label": "Classification",
              "widget": "choicesjs",
              "tableView": true,
              "multiple": true,
              "data": {
                "values": [{"label": "Animalia", "value": "animalia"}, {
                  "label": "Archaea",
                  "value": "archaea"
                }, {"label": "Bacteria", "value": "bacteria"}, {
                  "label": "Chromista",
                  "value": "chromista"
                }, {"label": "Fungi", "value": "fungi"}, {"label": "Plantae", "value": "plantae"}, {
                  "label": "Protozoa",
                  "value": "protozoa"
                }], "json": "", "url": "", "resource": "", "custom": ""
              },
              "validate": {
                "required": true,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "onlyAvailableItems": false
              },
              "key": "classification",
              "type": "select",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "attributes": [],
              "validateOn": "change",
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "idPath": "id",
              "clearOnRefresh": false,
              "limit": 100,
              "dataSrc": "values",
              "valueProperty": "",
              "lazyLoad": true,
              "filter": "",
              "searchEnabled": true,
              "searchDebounce": 0.3,
              "searchField": "",
              "minSearch": 0,
              "readOnlyValue": false,
              "authenticate": false,
              "ignoreCache": false,
              "template": "<span>{{ item.label }}</span>",
              "selectFields": "",
              "selectThreshold": 0.3,
              "uniqueOptions": false,
              "fuseOptions": {"include": "score", "threshold": 0.3},
              "indexeddb": {"filter": []},
              "customOptions": [],
              "useExactSearch": false,
              "id": "ef34cba"
            }], "width": 6, "offset": 0, "push": 0, "pull": 0, "size": "md", "currentWidth": 6
          }, {"components": [], "width": 6, "offset": 0, "push": 0, "pull": 0, "size": "md", "currentWidth": 6}],
          "key": "columns1",
          "type": "columns",
          "input": false,
          "tableView": false,
          "placeholder": "",
          "prefix": "",
          "customClass": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "hidden": false,
          "clearOnHide": false,
          "refreshOn": "",
          "redrawOn": "",
          "modalEdit": false,
          "dataGridLabel": false,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": null,
          "attributes": [],
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "conditional": {"show": null, "when": null, "eq": ""},
          "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "properties": [],
          "allowMultipleMasks": false,
          "addons": [],
          "tree": false,
          "lazyLoad": false,
          "autoAdjust": false,
          "id": "e9el91x"
        }, {
          "label": "Columns",
          "columns": [{
            "components": [{
              "label": "Rank",
              "widget": "html5",
              "tableView": true,
              "defaultValue": ["species"],
              "data": {
                "values": [{"label": "Species", "value": "species"}, {
                  "label": "Genus",
                  "value": "genus"
                }, {"label": "Infraspecific", "value": "infraspecific"}, {
                  "label": "Subdivision of genus",
                  "value": "subdivisionOfGenus"
                }], "json": "", "url": "", "resource": "", "custom": ""
              },
              "validate": {
                "required": true,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "onlyAvailableItems": false
              },
              "key": "rank",
              "type": "select",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "attributes": [],
              "validateOn": "change",
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "idPath": "id",
              "clearOnRefresh": false,
              "limit": 100,
              "dataSrc": "values",
              "valueProperty": "",
              "lazyLoad": true,
              "filter": "",
              "searchEnabled": true,
              "searchDebounce": 0.3,
              "searchField": "",
              "minSearch": 0,
              "readOnlyValue": false,
              "authenticate": false,
              "ignoreCache": false,
              "template": "<span>{{ item.label }}</span>",
              "selectFields": "",
              "selectThreshold": 0.3,
              "uniqueOptions": false,
              "fuseOptions": {"include": "score", "threshold": 0.3},
              "indexeddb": {"filter": []},
              "customOptions": [],
              "useExactSearch": false,
              "id": "ekl943d"
            }, {
              "label": "Type",
              "optionsLabelPosition": "right",
              "inline": true,
              "tableView": false,
              "values": [{"label": "extant", "value": "extant", "shortcut": ""}, {
                "label": "fossil",
                "value": "fossil",
                "shortcut": ""
              }],
              "validate": {
                "required": true,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "onlyAvailableItems": false
              },
              "key": "type",
              "type": "radio",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": null,
              "attributes": [],
              "validateOn": "change",
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "inputType": "radio",
              "fieldSet": false,
              "id": "efj7obh"
            }, {
              "label": "Type",
              "optionsLabelPosition": "right",
              "inline": true,
              "tableView": false,
              "values": [{"label": "terrestrial", "value": "terrestrial", "shortcut": ""}, {
                "label": "marine",
                "value": "marine",
                "shortcut": ""
              }, {"label": "freshwater", "value": "freshwater", "shortcut": ""}, {
                "label": "N/A",
                "value": "nA",
                "shortcut": ""
              }],
              "key": "type1",
              "type": "radio",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": null,
              "attributes": [],
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "onlyAvailableItems": false
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "inputType": "radio",
              "fieldSet": false,
              "id": "ezgxier"
            }, {
              "label": "Symbiotic with",
              "tableView": true,
              "key": "symbioticWith",
              "type": "textfield",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": [],
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": ""
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
              "id": "e3cogk8"
            }, {
              "label": "Parasite of",
              "tableView": true,
              "key": "parasiteOf",
              "type": "textfield",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": [],
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": ""
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
              "id": "e09j7o"
            }], "width": 6, "offset": 0, "push": 0, "pull": 0, "size": "md", "currentWidth": 6
          }, {
            "components": [{
              "label": "Type of treatment*",
              "widget": "html5",
              "tableView": true,
              "defaultValue": "newTaxon",
              "data": {
                "values": [{
                  "label": "New taxon",
                  "value": "newTaxon"
                }, {
                  "label": "Redescription or species observation",
                  "value": "redescriptionOrSpeciesObservation"
                }, {
                  "label": "New combination (comb. nov) with a legitimate basionym",
                  "value": "newCombinationCombNovWithALegitimateBasionym"
                }, {
                  "label": "New rank (stat. nov.) with a legitimate basionym",
                  "value": "newRankStatNovWithALegitimateBasionym"
                }, {
                  "label": "Replacement name (nom. nov.) for a legitimate or illegitimate synonym",
                  "value": "replacementNameNomNovForALegitimateOrIllegitimateSynonym"
                }], "json": "", "url": "", "resource": "", "custom": ""
              },
              "key": "typeOfTreatment",
              "type": "select",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "attributes": [],
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "onlyAvailableItems": false
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "idPath": "id",
              "clearOnRefresh": false,
              "limit": 100,
              "dataSrc": "values",
              "valueProperty": "",
              "lazyLoad": true,
              "filter": "",
              "searchEnabled": true,
              "searchDebounce": 0.3,
              "searchField": "",
              "minSearch": 0,
              "readOnlyValue": false,
              "authenticate": false,
              "ignoreCache": false,
              "template": "<span>{{ item.label }}</span>",
              "selectFields": "",
              "selectThreshold": 0.3,
              "uniqueOptions": false,
              "fuseOptions": {"include": "score", "threshold": 0.3},
              "indexeddb": {"filter": []},
              "customOptions": [],
              "useExactSearch": false,
              "id": "e2x359a"
            }, {
              "label": "Feeds on",
              "tableView": true,
              "key": "feedsOn",
              "type": "textfield",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": [],
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": ""
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
              "id": "e58550c"
            }, {
              "label": "Host of",
              "tableView": true,
              "key": "hostOf",
              "type": "textfield",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": [],
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": ""
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
              "id": "ezitczmn"
            }], "width": 6, "offset": 0, "push": 0, "pull": 0, "size": "md", "currentWidth": 6
          }],
          "key": "columns",
          "type": "columns",
          "input": false,
          "tableView": false,
          "placeholder": "",
          "prefix": "",
          "customClass": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "hidden": false,
          "clearOnHide": false,
          "refreshOn": "",
          "redrawOn": "",
          "modalEdit": false,
          "dataGridLabel": false,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": null,
          "attributes": [],
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false
          },
          "conditional": {"show": null, "when": null, "eq": ""},
          "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "properties": [],
          "allowMultipleMasks": false,
          "addons": [],
          "tree": false,
          "lazyLoad": false,
          "autoAdjust": false,
          "id": "etafnuv"
        }]
      },
      "sections": [{
        "id": 58,
        "name": "[MM] Taxon Name",
        "label": "Taxon Name",
        "schema": {"components": []},
        "sections": [{
          "id": 69,
          "name": "[MM] Taxon name",
          "label": "Taxon name",
          "schema": {
            "components": [{
              "label": "Columns",
              "columns": [{
                "components": [{
                  "label": "Genus",
                  "placeholder": " ",
                  "tableView": true,
                  "key": "genus",
                  "type": "textfield",
                  "input": true,
                  "prefix": "",
                  "customClass": "",
                  "suffix": "",
                  "multiple": false,
                  "defaultValue": null,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "hidden": false,
                  "clearOnHide": true,
                  "refreshOn": "",
                  "redrawOn": "",
                  "modalEdit": false,
                  "dataGridLabel": false,
                  "labelPosition": "top",
                  "description": "",
                  "errorLabel": "",
                  "tooltip": "",
                  "hideLabel": false,
                  "tabindex": "",
                  "disabled": false,
                  "autofocus": false,
                  "dbIndex": false,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "calculateServer": false,
                  "widget": {"type": "input"},
                  "attributes": [],
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "custom": "",
                    "customPrivate": false,
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                    "minLength": "",
                    "maxLength": "",
                    "pattern": ""
                  },
                  "conditional": {"show": null, "when": null, "eq": ""},
                  "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
                  "allowCalculateOverride": false,
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "properties": [],
                  "allowMultipleMasks": false,
                  "addons": [],
                  "mask": false,
                  "inputType": "text",
                  "inputFormat": "plain",
                  "inputMask": "",
                  "displayMask": "",
                  "spellcheck": true,
                  "truncateMultipleSpaces": false,
                  "id": "ebu4c99"
                }], "width": 4, "offset": 0, "push": 0, "pull": 0, "size": "md", "currentWidth": 4
              }, {
                "components": [{
                  "label": "Subgenus",
                  "placeholder": " ",
                  "tableView": true,
                  "key": "subgenus",
                  "type": "textfield",
                  "input": true,
                  "prefix": "",
                  "customClass": "",
                  "suffix": "",
                  "multiple": false,
                  "defaultValue": null,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "hidden": false,
                  "clearOnHide": true,
                  "refreshOn": "",
                  "redrawOn": "",
                  "modalEdit": false,
                  "dataGridLabel": false,
                  "labelPosition": "top",
                  "description": "",
                  "errorLabel": "",
                  "tooltip": "",
                  "hideLabel": false,
                  "tabindex": "",
                  "disabled": false,
                  "autofocus": false,
                  "dbIndex": false,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "calculateServer": false,
                  "widget": {"type": "input"},
                  "attributes": [],
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "custom": "",
                    "customPrivate": false,
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                    "minLength": "",
                    "maxLength": "",
                    "pattern": ""
                  },
                  "conditional": {"show": null, "when": null, "eq": ""},
                  "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
                  "allowCalculateOverride": false,
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "properties": [],
                  "allowMultipleMasks": false,
                  "addons": [],
                  "mask": false,
                  "inputType": "text",
                  "inputFormat": "plain",
                  "inputMask": "",
                  "displayMask": "",
                  "spellcheck": true,
                  "truncateMultipleSpaces": false,
                  "id": "e19boxh"
                }], "width": 4, "offset": 0, "push": 0, "pull": 0, "size": "md", "currentWidth": 4
              }, {
                "components": [{
                  "label": "Species",
                  "placeholder": " ",
                  "tableView": true,
                  "key": "species",
                  "type": "textfield",
                  "input": true,
                  "prefix": "",
                  "customClass": "",
                  "suffix": "",
                  "multiple": false,
                  "defaultValue": null,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "hidden": false,
                  "clearOnHide": true,
                  "refreshOn": "",
                  "redrawOn": "",
                  "modalEdit": false,
                  "dataGridLabel": false,
                  "labelPosition": "top",
                  "description": "",
                  "errorLabel": "",
                  "tooltip": "",
                  "hideLabel": false,
                  "tabindex": "",
                  "disabled": false,
                  "autofocus": false,
                  "dbIndex": false,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "calculateServer": false,
                  "widget": {"type": "input"},
                  "attributes": [],
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "custom": "",
                    "customPrivate": false,
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                    "minLength": "",
                    "maxLength": "",
                    "pattern": ""
                  },
                  "conditional": {"show": null, "when": null, "eq": ""},
                  "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
                  "allowCalculateOverride": false,
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "properties": [],
                  "allowMultipleMasks": false,
                  "addons": [],
                  "mask": false,
                  "inputType": "text",
                  "inputFormat": "plain",
                  "inputMask": "",
                  "displayMask": "",
                  "spellcheck": true,
                  "truncateMultipleSpaces": false,
                  "id": "epfflmh"
                }], "size": "md", "width": 4, "offset": 0, "push": 0, "pull": 0, "currentWidth": 4
              }],
              "key": "columns",
              "type": "columns",
              "input": false,
              "tableView": false,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": false,
              "hidden": false,
              "clearOnHide": false,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": null,
              "attributes": [],
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "tree": false,
              "lazyLoad": false,
              "autoAdjust": false,
              "id": "elqvlfs"
            }, {
              "label": "Columns",
              "columns": [{
                "components": [{
                  "label": "Taxon Author(s) and year",
                  "placeholder": " ",
                  "tableView": true,
                  "key": "taxonAuthorSAndYear",
                  "type": "textfield",
                  "input": true,
                  "prefix": "",
                  "customClass": "",
                  "suffix": "",
                  "multiple": false,
                  "defaultValue": null,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "hidden": false,
                  "clearOnHide": true,
                  "refreshOn": "",
                  "redrawOn": "",
                  "modalEdit": false,
                  "dataGridLabel": false,
                  "labelPosition": "top",
                  "description": "",
                  "errorLabel": "",
                  "tooltip": "",
                  "hideLabel": false,
                  "tabindex": "",
                  "disabled": false,
                  "autofocus": false,
                  "dbIndex": false,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "calculateServer": false,
                  "widget": {"type": "input"},
                  "attributes": [],
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "custom": "",
                    "customPrivate": false,
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                    "minLength": "",
                    "maxLength": "",
                    "pattern": ""
                  },
                  "conditional": {"show": null, "when": null, "eq": ""},
                  "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
                  "allowCalculateOverride": false,
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "properties": [],
                  "allowMultipleMasks": false,
                  "addons": [],
                  "mask": false,
                  "inputType": "text",
                  "inputFormat": "plain",
                  "inputMask": "",
                  "displayMask": "",
                  "spellcheck": true,
                  "truncateMultipleSpaces": false,
                  "id": "erlmgt"
                }], "width": 9, "offset": 0, "push": 0, "pull": 0, "size": "md", "currentWidth": 9
              }, {"components": [], "width": 3, "offset": 0, "push": 0, "pull": 0, "size": "md", "currentWidth": 3}],
              "key": "columns1",
              "type": "columns",
              "input": false,
              "tableView": false,
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": false,
              "hidden": false,
              "clearOnHide": false,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": null,
              "attributes": [],
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""},
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": [],
              "allowMultipleMasks": false,
              "addons": [],
              "tree": false,
              "lazyLoad": false,
              "autoAdjust": false,
              "id": "eopa0nh"
            }]
          },
          "sections": null,
          "template": "<inline-block-container style=\"display: block;font-weight:700;\">\n <form-field formControlName=\"genus\">\n </form-field>\n <form-field formControlName=\"subgenus\">\n </form-field>\n <form-field formControlName=\"species\">\n </form-field>\n <form-field formControlName=\"taxonAuthorSAndYear\">\n </form-field>\n </inline-block-container>",
          "type": 0,
          "version_id": 473,
          "version": 3,
          "version_pre_defined": false,
          "version_date": "2022-05-03T04:12:10.000000Z",
          "complex_section_settings": null,
          "settings": null,
          "compatibility": null,
          "created_at": "2022-05-02T21:22:05.000000Z"
        }],
        "template": "<div></div>",
        "type": 1,
        "version_id": 454,
        "version": 16,
        "version_pre_defined": false,
        "version_date": "2022-05-02T21:22:23.000000Z",
        "complex_section_settings": [],
        "settings": null,
        "compatibility": {
          "allow": {"all": false, "values": [57, 49, 50, 59, 69]},
          "deny": {"all": false, "values": []}
        },
        "created_at": "2022-04-20T21:39:03.000000Z"
      }],
      "template": "<b><h3 contenteditableNode=\"false\">Taxon Treatment</h3></b>",
      "type": 1,
      "version_id": 471,
      "version": 8,
      "version_pre_defined": true,
      "version_date": "2022-05-03T04:09:09.000000Z",
      "complex_section_settings": [],
      "settings": {"main_section": true},
      "compatibility": {"allow": {"all": false, "values": [58]}, "deny": {"all": false, "values": []}},
      "created_at": "2022-04-20T21:59:48.000000Z"
    })
    this.sectionTemplates = this.data.templates
  }

  chooseSection(val: any) {
    if (!val) {
      this.showError = true
      setTimeout(() => {
        this.showError = false
      }, 1000)
    } else {
      this.dialogRef.close(val)
    }
  }

  closeSectionChoose() {
    this.dialogRef.close()
  }

  public search(value: any) {
    this.value = value
  }

}
